force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LOAN-{0000}</displayFormat>
        <label>Loan Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LoanAssignmentService.cls
public with sharing class LoanAssignmentService {
    public LoanAssignmentService() {

    }
     public static void assignAgent(List<Loan_Application__c> loans) {
        if (loans == null || loans.isEmpty()) return;

        List<User> agents = [
    SELECT Id
    FROM User
    WHERE IsActive = true
    AND UserType = 'Standard'
    AND Profile.Name LIKE '%Agent%'
    LIMIT 1
];



        if (agents.isEmpty()) return;

        for (Loan_Application__c loan : loans) {
            if (loan.User__c == null) {
                loan.User__c = agents[0].Id;
            }
        }
    }
}